document:
    name: "Dati sulla mobilità della Città di Padova"
    description: "Il seguente documento riepiloga i dati statistici sulla mobilità della Città di Padova"
    author: peterampazzo
    license: CC-BY 4.0
    tags:
      - digital
      - transportation
      - citizenship
      - data
